<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>model</string>
	</array>
	<key>name</key>
	<string>Model</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#types</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#message</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#packaging</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)\b</string>
			<key>name</key>
			<string>constant.numeric.model</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.model</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.model</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|max)\b</string>
			<key>name</key>
			<string>constant.language.model</string>
		</dict>
		<key>message</key>
		<dict>
			<key>begin</key>
			<string>(model|extend)(\s+)([A-Za-z][A-Za-z0-9_.]*)(\s*)(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.model</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.message.model</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#modifiers</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#validation</string>
				</dict>
				<dict>
					<key>patterns</key>
					<array>
						<dict>
							<key>captures</key>
							<dict>
								<key>1</key>
								<dict>
									<key>name</key>
									<string>entity.name.class.model</string>
								</dict>
								<key>4</key>
								<dict>
									<key>name</key>
									<string>storage.name.class.model</string>
								</dict>
							</dict>
							<key>match</key>
							<string>([A-Za-z][A-Za-z0-9_]*:)(\s*)(\[?)([a-zA-Z][a-zA-Z0-9_]*)(\]?)</string>
						</dict>
						<dict>
							<key>include</key>
							<string>#storagetypes</string>
						</dict>
						<dict>
							<key>begin</key>
							<string>\[</string>
							<key>end</key>
							<string>\]</string>
							<key>patterns</key>
							<array>
								<dict>
									<key>match</key>
									<string>default|packed|deprecated|lazy</string>
									<key>name</key>
									<string>keyword.source.model</string>
								</dict>
								<dict>
									<key>include</key>
									<string>#constants</string>
								</dict>
							</array>
						</dict>
					</array>
				</dict>
			</array>
		</dict>
		<key>modifiers</key>
		<dict>
			<key>match</key>
			<string>\b(index|required|unique|readonly)\b</string>
			<key>name</key>
			<string>keyword.source.model</string>
		</dict>
		<key>packaging</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.model</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(package|import)(?=(\s+)(["]?[A-Za-z][A-Za-z0-9_./]*["]?)(;)?)</string>
		</dict>
		<key>storagetypes</key>
		<dict>
			<key>match</key>
			<string>\b(double|float|int|uint|int32|int64|uint32|uint64|bool|string|bytes|id)\b</string>
			<key>name</key>
			<string>storage.type.model</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.model</string>
		</dict>
		<key>types</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.model</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(types)(\s*)(\"?[A-Za-z][A-Za-z0-9_.\s/]*\"?\s*)</string>
		</dict>
		<key>validation</key>
		<dict>
			<key>begin</key>
			<string>(validate|extend)(\s+)(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>string.unquoted.model</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#validators</string>
				</dict>
			</array>
		</dict>
		<key>validators</key>
		<dict>
			<key>match</key>
			<string>\b(range|length|email|url|pattern)\b</string>
			<key>name</key>
			<string>variable.language.model</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.model</string>
	<key>uuid</key>
	<string>750ac1f3-b172-48de-b1a4-a3c310c4a293</string>
</dict>
</plist>
